apiVersion: v1
kind: Secret
metadata:
  name: modern-blog-secret
  namespace: modern-blog
type: Opaque
stringData:
  DATABASE_URL: "postgresql://blog:change-me@postgres.modern-blog.svc.cluster.local:5432/modern_blog?schema=public"
  NEXTAUTH_SECRET: "replace-with-random-secret"
  GITHUB_ID: ""
  GITHUB_SECRET: ""
  GOOGLE_ID: ""
  GOOGLE_SECRET: ""
  ADMIN_EMAILS: ""
